require 'rubygems'
require 'spec'
require 'spec/rake/spectask'
require 'rake/gempackagetask'
require 'pathname'

PLUGIN = "merb_datamapper"
NAME = "merb_datamapper"
VERSION = "0.9.3"
AUTHOR = "Jason Toy"
EMAIL = "jtoy@rubynow.com"
HOMEPAGE = "http://datamapper.org"
SUMMARY = "DataMapper plugin that provides DataMapper support for Merb"

spec = Gem::Specification.new do |s|
  s.name = NAME
  s.version = VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.add_dependency('merb-core', '>= 0.9.2')
  s.add_dependency('dm-core', '>= 0.9.0')
  s.require_path = 'lib'
  s.autorequire = PLUGIN
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,spec,datamapper_generators}/**/*")
end

task :default => :spec

windows = (PLATFORM =~ /win32|cygwin/) rescue nil

SUDO = windows ? "" : "sudo"

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

desc "Install #{NAME} #{VERSION}"
task :install => :package do
  sh %{#{'sudo' unless ENV['SUDOLESS']} gem install pkg/#{NAME}-#{VERSION} --no-rdoc --no-ri --no-update-sources}
end

desc 'Release the current version on rubyforge'
task :release => :package do
  sh %{rubyforge add_release merb #{PLUGIN} #{VERSION} pkg/#{NAME}-#{VERSION}.gem}
end

desc "Run specifications"
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_opts << '--format' << 'specdoc' << '--colour'
  t.spec_files = Pathname.glob(Pathname.new(__FILE__).parent + 'spec/**/*_spec.rb')
end
