#!/bin/sh

for gemdir in dm-*; do
  pushd .
  cd $gemdir

  # clean up files we don't want appearing in Manifest.txt
  rake clean
  rm -r **/*.sql
  rm -rf pkg

  # TODO: this has a little problem
  # check_manifest prints commands it runs
  # first so when diff is empty, garbage is sent to patch
  # via pipe
  #
  # it makes no harm but better be handled somehow
  rake check_manifest | patch -p0 Manifest.txt
  git add Manifest.txt
  git ci -m "[$gemdir] Updated Hoe's Manifest"

  popd
done