require 'rubygems'
require 'spec'
# require 'merb-core'
require 'dm-core'
require 'dm-validations'
require File.dirname(__FILE__) + '/../lib/dm-tags'
require File.dirname(__FILE__) + '/classes'
require File.dirname(__FILE__) + '/dm-setup'
